# Generated by Django 2.2.6 on 2020-01-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delay',
            field=models.IntegerField(verbose_name='Отправить через (сек)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(verbose_name='Текст сообшения'),
        ),
    ]
